name: Testes Unitários

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Preparar workaround do npm
        run: |
          rm -rf package-lock.json node_modules

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Rodar testes com Vitest
        run: npx vitest run --coverage
